steps:
  - name: node:10.20.1
    entrypoint: npm
    args: ['install']
  - name: node:10.20.1
    entrypoint: npm
    args: ['run', 'build']
  - name: node:10.20.1
    entrypoint: npm
    args: ['run', 'create-env']
    env:
      - '_DEV=${_DEV}'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
timeout: '1600s'
