steps:
- name: node:10.20.1
  entrypoint: npm
  args: ["install"]
- name: node:10.20.1
  entrypoint: npm
  args: ["build"]
- name: node:10.20.1
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - '_DEV=${_MY_SECRET_KEY}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"